### ISSUE TITLE
1.3 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#1]
- [x] 출시 날짜가 비어있는 넨도를 찜하거나 보유로 처리했을 때 마이페이지 오류 현상
- [x] 업데이트 도중에 실패 시 업데이트를 진행 할 수 없는 문제
- [ ] ~~다운로드 속도 개선 가능한지 검토~~
- [x] 넨도에 메모기능 추가
- [x] Firebase Crashlytics 추가
- [x] 넨도번호로 검색 가능하도록 수정, 영문 검색시 대소문자를 가리지 않도록 수정
