### ISSUE TITLE
1.5 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#14]
- [x] 컨트롤러부분 리펙토링 (화면별로 controller를 만들고 nendoController를 경량화)
- [x] 위젯부분 리펙토링
- [x] 보유 넨도 체크시 수량 0으로 시작하는 버그 수정
- [x] 바텀시트높이를 wrap_content 사이즈가 되도록 수정
- [x] 메인화면에서 뒤로가기 버튼의 동작을 변경
