### ISSUE TITLE
1.6 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#19]
- [x] 많이 가지고 있는 시리즈 위쪽에 공백 2배로 적용된거 제거
- [x] 현재 버전 보여주고 update 기능 구현
- [x] 같은 번호일 경우 하나만 가지고 있어도 세트 컴플리트 되도록 수정
- [x] 다운로드현황이 보이지 않는 문제
