### ISSUE TITLE
2.1 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#27]
- [x] 앱 업데이트 오류 수정
- [x] 디시인사이드 크롤링
- [x] 루리웹 크롤링
- [x] 트위터 한스마, 니니멀 계정 추가
- [x] 원하는 계정만 소식받기
