### ISSUE TITLE
2.3 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#35]
- [x] 트위터 게시물 링크 적용 및 개행이 안되어있는 현상 수정
- [x] 넨도리스트 아이템 클릭시 바로 굿스마 홈페이지로 이동하지 않고 앱내에서 상세보기를 보여주도록 수정
- [x] 구입가격 입력시 콤마생성
- [x] 앱버전이 릴리즈 모드에서 안보이는 문제 수정
- [x] 트위터 네트워크 오류 처리 좀 더 상세하게 처리
- [x] 엔화환율정보 변경 (해외 송금 금액으로)
- [x] 시작시 안내 팝업을 띄울 수 있도록 remote config 기능 추가
- [x] 업데이트 알림 팝업을 띄울때 업데이트 사항을 표시할 수 있도록 수정
