### ISSUE TITLE
2.4 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#43]
- [x] 검색이나 필터 적용상태로 업데이트를 진행하면 데이터가 날아가는 문제 수정
- [x] 일부 넨도로이드가 상세 정보 로드가 안되는현상 수정
- [x] 파이어스토어에 기본 넨도 데이터를 저장하고 깃허브를 거치지 않고 바로 다운로드
- [x] 로그인 기능 추가 + 데이터 백업 기능 추가
