### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#47]
- [x] 넨도 데이터가 커졌을때 파이어스토어에 저장을 할 수 없는 문제 수정필요
- [ ] 이메일주소 변경 기능 만들기
- [x] GridListView로 목록 보여주기, 텍스트로만 목록 보여주기
- [x] play-services-safetynet (com.google.android.gms:play-services-safetynet) 개발자가 SDK 버전 17.0.0에 다음 메모를 추가했습니다.
- [x] 파베관련 다 업데이트
- [ ] IOS FCM 추가
- [x] Material3 테마 적용
- [x] 도쿄리벤져스 넨도 정보 안뜨는 문제
- [x] 문의사항 추가
2098 나가토로양 F
