### ISSUE TITLE
아주 먼 미래에 TODO List

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#68]
- [ ] 파이어베이스에서 굿스마일의 출하 일정을 주기적으로 스크래핑 후 앱에서 캘린더 형식으로 출하일정 제공
- [ ] 유저가 사진을 올리고 다른사람들이 그 사진을 볼 수 있는 기능
- [ ] 넨도로이드의 특징 (머리색, 머리모양, 표정파츠)을 태그 형식으로 달아서 검색기능을 확장
- [ ] 넨도로이드 이미지 학습을 시켜서 사진을 찍었을때 어떤 넨도로이드인지 판별
- [ ] 넨도로이드의 평점과 한줄평을 입력받을 수 있도록 하기
