### ISSUE TITLE
1.4 todo list

### ISSUE THREAD

**Issue by silvershort** [silvershort/nendoroidList#9]
- [ ] ~~백그라운드 다운로드 구현~~
- [ ] ~~스크롤 모드 추가 (스크롤시 앱바와 바텀네비바를 숨겨줌)~~
- [x] 다크모드하면 실행안되는 버그?
- [x] 아이템 높이를 고정크기로 하지 않고 유동적으로 변하도록 수정
